---
title: Haiku
author: Mariana Montes
date: '2021-08-21'
slug: haiku
categories:
  - fiction
tags: []
subtitle: ''
summary: 'Cuento que escrib칤 hace muchos a침os, inspirada por Genji y mis propias fantas칤as.'
authors: []
lastmod: '2021-08-21T23:04:12+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

*Escrib칤 este cuento el 11 de abril de 2010 ---al menos es la fecha al final del archivo original. Hab칤a estado leyendo la Historia de Genji traducida la espa침ol, donde los personajes intercambiaban a menudo peque침os mensajitos con expresiones muy curiosas, como "mangas h칰medas" para indicar que hab칤an estado llorando. En ese esp칤ritu, decid칤 escribir un cuento que usaba haikus, pero tambi칠n, por primera vez, darle un toque personal.*

*El haiku es un poema japon칠s de 17 s칤labas (que pueden estar organizadas en versos de cinco, siete y cinco s칤labas) que describe con sencillez --no necesariamente simpleza-- algo cotidiano o natural. Con pocas palabras manifiesta la profundidad de algo aparentemente trivial... en general, las estaciones.*

<hr>

---En luz helada, /en silencio y vac칤o, /un grillo canta ---observ칩 el esp칤ritu poeta con un dejo de melancol칤a.

---Ten칠s raz칩n ---aprob칩 su compa침ero sin mucha preocupaci칩n---. La 칰nica alma que percibo en esa casa es la de 칠l, y se hunde en desesperaci칩n.

Evalu칩 la situaci칩n con frialdad intelectual, oyendo el canto del grillo que retumbaba en la soledad del hombre.

---Mueren sus ojos /en la total ausencia /de vida humana ---dijo luego el poeta, y su compa침ero asinti칩.

---Pero supongo que si prende las luces va a notar todo vac칤o, todo artificial y opuesto a lo que est치 sintiendo, 쯡o?

---Porta consigo /incontrolablemente /mangas h칰medas.

---쯊e parece? ---dijo el otro con un dejo de duda---. Yo no veo que est칠 llorando, pero si vos lo dec칤s, as칤 debe ser. Est치 solo, y est치 frustrado: lo comprendo.

---Brilla el fuego /tan solitariamente /cerca del agua ---suspir칩 el poeta. Hubo una pausa pesada antes de la respuesta, en la que el otro esp칤ritu hizo el equivalente a fruncir el ce침o, morderse el labio y rascarse la cabeza.

---Ah칤 no caigo ---exclam칩 finalmente, y continu칩 con la voz cargada de admiraci칩n---. Vos siempre ves m치s all치... 쯗ec칤s que ella lo dej칩 porque eran incompatibles? 쯆 habl치s de la pava?

El poeta hizo el equivalente a sacudir la cabeza, descubriendo como siempre que su colega esp칤ritu era un caso perdido. Hablaba descontroladamente, con ese voseo insoportable, ve칤a tanto como un humano normal y hac칤a de cuenta que estaban manteniendo una conversaci칩n. 쯅o lo dec칤a todo 칠l con sus haiku, acaso?

---Las flores caen /se desnuda la tierra: /ya es invierno ---dijo al final.

---Ella, que es toda su vida y su belleza, falta ---asinti칩 el otro---. 칄l queda solo y fr칤o como tierra yerma y... par치.

Pararon. Todo se detuvo. Su campo de visi칩n se desvi칩 unos metros.

---Ah칤 volvi칩. Mirala, 춰entr칩 nom치s! Est치 prendiendo la luz.

---Che, amor, se cort칩 la luz, 쯤uer칠s que vayamos al patio? ---grit칩 a toda potencia la mujer, que tra칤a una bolsa en la mano.

---Dale ---respondi칩 el hombre desde el oscuro fondo de la casa.

Ella barri칩 la cocina con la mirada, y mientras volcaba el contenido de la bolsa (facturas y criollos) en una panera su mirada encontr칩 la pava sobre el fuego. Frunci칩 el entrecejo y exclam칩 con fingida indignaci칩n:

---쯈u칠 significa esto? 쯅o est치 listo el mate?

El hombre apareci칩 mir치ndose la mano, y extendi칩 su brazo para que ella tambi칠n la mirara.

---Me quem칠 ---explic칩---: se me volc칩 la pava encima, y hace un rato puse m치s agua a calentar.

Ella observ칩 la manga del buzo, h칰meda, cubriendo la mu침eca enrojecida, y la bes칩 delicadamente. Lo mir칩 a la cara con ternura y le puso una medialuna en la boca.
El poeta observ칩 la escena at칩nito, abrumado. Sent칤a la sonrisa del hombre, sent칤a lo que pasaba en su interior, tal como lo hab칤a sentido antes.

---Las nubes huyen /dando paso en el cielo /a media luna ---enton칩 con admiraci칩n, enternecido por el efecto de la llegada de la mujer.

---Me encandila su alegr칤a ---dijo su compa침ero, casi con asco---. Dej칠moslos solos, que ya entre ellos se hacen suficiente compa침칤a.

Y el poeta tuvo que asentir (inconscientemente, ensimismado), y seguirlo, sin palabras.

{{% callout note %}}
Esta es tambi칠n la primera historia que escrib칤 en la que mis personajes tomaban mate 游븰.
{{% /callout %}}