---
title: "Housemate wanted"
author: "Mariana Montes"
date: '2021-08-17'
slug: housemate-wanted
categories: fiction
tags: []
subtitle: ''
summary: 'This is a short story inspired by the "Mundial de la Escritura" (in which I am not participating). The original is in English!'
lastmod: "`r Sys.time()`"
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r, include = FALSE}
library(fontawesome)
up <- fontawesome::fa("star", fill = "#FFC300")
down <- fontawesome::fa("star", fill = "#98978b")
```

I was sick of living alone. I couldn't take it anymore. I never thought I would say that, because I enjoy having my own space, I can spend hours reading or watching Netfix and YouTube or drawning in Twitter, but if the pandemic taught me anything was that I need company. I want to sit and have maté with someone, I want to be cuddled while watching dramas, I want to come home one day to a homemade dinner.

The loneliness was draining me, but it would not go away by itself, so I decided to look for a place to move. A place *where someone lived already*. I found a couple of forums where people searched for housemates: they would offer ar oom and shared kitchen and bathroom, and you just had to pay half the rent. I lied on the sofa with the laptop on my lap and started browsing the posts, increasingly yawning and with my eyelids getting heavier every minute. My desire for company competed with my reluctance to share my home with someone I didn't know. What is more, these guys had all kinds of requirements and the filter panel on the site was a disaster. No smoking, tolerate smokers, no noise after ten pm, tolerate noise until four am, no animals, no people allergic to cats, sweet maté drinkers, vegetarians, French-speaking...
Those without specific requirements were the most suspicious ---at least, they gave no clues as to the kind of people they were. When I wrote to one of them she asked me for a picture and right after I sent it responded that she "had already found someone else". Another one asked to see a picture of my library and then said that I should probably invest a bit more in philosophy before contacting him again. A third house without requirements had so many crosses and rosaries in the pictures of the rooms that I had to get up and get some more maté before going any further.

I don't know how many houses I checked before giving up, it felt like forever. I was about to close the site and get up to make dinner when I saw the picture of the cutest cottage ever and had to click on it.

> Cottage with park and a gallery (hammock included), three bedrooms, kitchen with island and multilingual library. Closed garage, space for bikes and three covered doghouses. Two bedrooms available for whoever wants to share the space with me. Unfortunately, there is no accessibility for wheelchairs at the moment. Requirements: no smoking, keeping order in the common spaces, no breaking furniture, no setting the kitchen on fire, no rejecting stray animals.

The pictures where adorable. There was a livingroom with wallpaper, a huge clock and a magnificent stone hearth. The "library" was a full room completely covered with shelves, with more books than I had ever read. The view from the bedroom windows was a deep green, with a dozen trees between the house and the road. And the price was exactly what I was willing to pay.

A bit suspicious. I had never heard of such a house and, even though it was not in my city, it was close enough that visiting would not be too hard. It was almost as if someone had read my mind... I thought of the algorithms of such search engines and that maybe it looked at what kind of houses I was interested in to create the ideal house and trap me. I checked the reviews, but there were none. I looked it up on Google Maps, to look for reviews there, and they were mostly negative. One from three years ago said that the area was not well illuminated, and another, older still, complained about a rusty fence. But they were old. A more recent one read:

> `r up` `r down` `r down` `r down` `r down`
>
> Too green, every sunday its full of people drinking mate among the trees and nobody kicks them out, but as soon as I took a smoke there was a scream like someone was gettin torturd.

I almost got maté up my nose. I moved on to the following review:

> `r up` `r up` `r down` `r down` `r down`
>
> Not a restaurat its a pirvate house.

> `r up` `r up` `r up` `r down` `r down`
> 
> No idea was never there.

Before my eyes went up to my brain from rolling them, I looked for a positive comment, and only found one, from a couple of days earlier.

> `r up` `r up` `r up` `r up` `r up`
>
> I came by yesterday, it was raining and I waited the storm out in the gallery. I was scared becaufe of the forest but it was ok, a stray came by and sat with me the whole time. No idea who lives here but they left me some tea on the window, thanks!

Convinced. I wrote to the account that had posted the request, and two minutes later they answered very nicely and sent me the PDF of the contract. There was no user information: the name was CabinInTheWoods666 and the profile picture was the magnificent clock. But I was convinced; I showed the contract to a friend who works on that, printed it, signed it, she certified it, I mailed it to the house and started planning the move. Two days later I received an envelope with my set of keys and a plastic jar with cookies that made my heart blossom, although they came from a bakery. My friend, Sandra, convinced me to send my furniture to a storage facility just in case, and I only took clothing and some personal stuff to my new home.

I was very curious about who would be my host, and I started to fantasize that she was about my age, liked horseback riding and poured mates that would not wash out. As I finished loading my stuff on my friend's car, I imagined that first moment as I arrived to the house, who would open the door for me: a soft figure with a wide smile, red hairs twisted around her head in an elaborate spiral braid from her forhead to the back of her neck, her shoulder, her chest. I imagined eyes the colour of the wood of the clock, whose name I can never remember. That dark, shiny one that only rich people can afford. A few blocks from the house we stopped by a traffic light in front of a lab, and I fantasized that was her workplace:

"Felipa Whatevername, chemist", she would introduce herself, and I would respond with something very clever, because in my fantasies I know how to talk to people.

"Any idea who you will be living with?", asked Sandra, interrupting my daydreaming.

"I don't know, but seems nice", I answered.

"Those cookies were very good", she agreed, "although from bakery. Do you want me to stay around with you, so I can drive you to my place if something goes wrong?"

I shook my head. I was sure it was going to work out.

The cabin looked as cute as in the pictures. The park shone under the afternoon sun, and the tall trees (poplar trees?) bordered the narrow entrance road, which did have a few bumps. Sandra parked in front of the porche and helped me to the entrance with the first load of baggage. I looked for a bell and rang it, but there was no answer. I knocked, in case the bell didn't work, but no use. I decided for my key, and we got in. The front door led to the living room, as fancy as in the pictures. The hearth was out but the clock on the wall worked. Some dust floated in the lightbeams coming from the window, but it was well ventilated. Next to the entrance there was a coat hanger, something like shelves for shoes, a delicate wall mirror and, glued to the mirror, a note.

> ¡Welcome home `r fontawesome::fa("heart", fill = "red")`! Your room is the second to the left on the top floor: the sheets are clean and there are extra blankets in the closet. There is no food in the kitchen so I wrote down some numbers for delivery if you don't want ot cook. The supermarket also has delivery and they are cool. The WiFi is HauntedCabin and the password is k8NdSPkf3.

After that there was a list of delivery numbers and that was it. No signature (what was their name?!) or information about when we would see aech other, whether they were out on a trip or what. But the text was really sweet, the WiFi name clever and the password good, although not very memorable. Sandra helped me bring my stuff to the bedroon, which had the most attractive bed, a small balcony with geranium plants and a wonderful view of the forest, heavy blackout curtains and a closet that could have taken me to Narnia, although I didn't dare try. We ordered some pizzas and Sandra hang out with me for a while, but then she had to go back home and I was by myself. Again.

The house had its positive aspects. First, it was beautiful. I loved every architectonic and design detail, from the whitish tone of the countertops to the size of the drawers, from the water pressure in the shower to the softness of the door handles, from the texture of the curtains to the shine of the linoleum covering the floors. But it was empty. I saw no sign of anyone living there: only one room, at the nd of the top floor corridor, which was locked.

The first night, after a good shower, I dropped on my bed and fell asleep instantly. The following day I put my clothes away in the closet while listening to music on my headphones ---after three songs I realized I could use the stereo and filled the house with country and pop. Slowly, the music got to me and I started dancing while hanging my coats, putting my shoes in order and sorting my stuffed animals on a shelf. 
I danced with an imaginary host around the bedroom and the corridor, down the stairs towards the kitchen, where I heated water for the maté. I set up my shopping list, selected the products from the supermarket's website and ordered its delivery (I didn't want to risk my housemate showing up right in my absence). I set up the mate and started exploring the house, my hips still governed by the music.

The livingroom I knew. On the entrance wall there was also a rather modern TV (probably a SmartTV) but it was unplugged; on the other side sat an L-shaped sofa, with a bit dusty but very comfortable cushions, surrounding a coffee table gathering dust over a pile of comics. The other branch of the L faced the hearth, which, although not on, looked functional, and was so huge I could've sat inside. It was a shelf on top but no pictures or decorations other than a sort of rectangular stone fixed to the wall and, on top of it, the magnificent clock with the pictures. In front of the hearth and the clock was the staircase, perpendicular to it, with an intriguing design. It was a bench built on the same material of the stairs, with thin cushions and, next to it, a cat-shaped pillar. As if a thin, elegant cat, two meters tall, sat next to the bench, alert ears touching the ceiling. Its material was strange, as if covered in suede. Even stranger was its location, as if someone would want to sit on the bench, next to the giant cat, to watch the clock or the fire in the hearth, but from the other side of the living room.

The ground floor had, then, the kitchen, the living room, the library, the most claustrophobic toilet in the world and a garage-pantry. The top floor had three bedrooms and the bathroom, which included a bathtub and shower, a wide counter with a mirror surrounded by tiny lightbulbs, toilet cup and bidet, and even a small sign of an arrow pointing to the switch for the extractor fan. One of the rooms was oven, mostly empty and unused, and if nobody stopped me I wanted to use it for home office, although its bed was rather tempting. The second room was by bedroom, and the third, the locked door at the end of the corridor, seemed not to have been open in decadeds, although it must be the other bedroom being used. There was also an attic with dust covered boardgames and a huge park that took me a whole afternoon to fully explore.

At the end of the second day Sandra called me as I was making dinner. I connected the headphones to the laptop and left it on a spot in the kitchen that let us see each other while I cooked.

"So? News from your 'housemate'?", she asked at once, with a cheerful tone but surely worried.

"Nothing", I answered while chopping the onion, "No message, no call, no sign of them in the house. I don't know, it's as if I'm living by myself again."

In some circumstances it can be useful to stimulate the lacrimal glands with onion and pretend there is nothing emotional going on there. I washed my hands and face and returned to the counter to chop ham, chicken breast and mushrooms.

"What a weird thing, he. Did you try writing to them again in SearchingCompany? That was the site, right?"

"Yeah, but it's no use. The account doesn't exist any more. Their texts in my conversation were erased, censored, I don't know."

"And you don't have any phone number?"

"Only the landline", I laughed, and went to wash my hands again before turnin on the stove under the pan. "I didn't think I would need any other means to contact them, you know. I looked back at the contract but there's only the address, and nothing else. I don't know, I'll just have to wait... It's a disappointment that's all."

I put some butter on the hot pan, and once it melted I started adding the onion, the chicken, the ham and the mushrooms, one by one, while Sandra and I exchanged hypothesies about what could have happened to my alleged host (who I often thought of as the woman of my dreams), from a family emergency on the other side of the country to an explosion in the lab where I thought she/they worked or even that the aliens had abducted her. It was Sandra who suggested it:

"What if the house is haunted and you are actually talking *to a ghost*?"

I swallowed a nervous laughter, squatting to get the flour from the counter so she wouldn't see how nervous my laughter really was.

"At least a ghost is better than being alone, right?", she said with as light a tone as she could master.

"I guess...", I mumbled, mixng the flour into the sauce, and focussing on adding milk and mixing, adding milk and mixing... I didn't want my ears to start searching for mysterious sounds, steps in an empty room, an unplugged TV turning on, or...

"Ok, hang on a sec", said Sandra, and her seriousness pulled me out of the trance.

"What is it?", I asked, lowering the fire under the pan and getting ready to knead the pasta. I put water to boil, installed the small pasta machine on the counter, pulled out the dough from the fridge, spread some flour and started cutting and flattening. On the laptop screen, Sandra stared with a frown: not at me, but at something she was looking up on her side.

"A few days ago I learned of a site called isithaunted.com", she said, her voice lost as she focused her attention on the search. "What was your address? Oaks..."

"Aspen avenue 3. isithaunted.com you said?"

"Yup", she answerd, still a bit distracted. "Ha! You can use Google Maps to search too. It has like colours and categories... Look. It checks if there are like ghost reports, or how frequently people move out..."

"Or whether someone died there...", is joked in disbelief, while turning the handle of the pasta machine longer than I needed to.

"Whether someone died there", Sandra confirmed, seriously, and suddenly screamed triumphantly, clapped... and went back to her confused expression. "It says 'undefined: it might be haunted, probability of 56%'."

"Alright, *probability*?", I asked, again in nervous laughter, and turned to add salt to the boiling water and drop the pasta in it.

"Yup", Sandra was very serious, as if reading a medical diagnosis. "it says there is no history of deaths... I mean, the first owner did die, but not in the house. Something like she went to visit her daughter and grandkids, stay the night and never woke up again. Nobody took care of the house, but someone rents a room now and then, somehow (on the internet like you, I guess) and two or three days later they leave..."

"Two or three days later?!", I screamed, almost dropping the dishes I so orderly was placing on a tray.

"Relax, I'm sure it's nothing", Sandra unsuccessfully tried to calm me down. "But in any case, you let me know. There are no reports on someone dying there, so I don't think you're in danger."

I looked at her in disbelief. Oh, ok, it might be a haunted house, but at least it wouldn't *kill* me.

"Ok, thanks", I said, somewhat coldly. "Dinner is ready, so I'm leaving you."

"You made a parisienne sauce", she noticed with a smile, dropping the subject. "Why the tray?"

"I'll eat outside in the gallery, the evening is quite nice. Good night!"

"Bon appetit", she said, and blew a kiss to the screen. "And take care."

I nodded, cut the connection and took my dinner to the gallery. The automatic light turned on as oon as I came out and for a moment gave me the chills. I stopped to breath deeply three times before going to the table and sitting down. The evening was indeed lovely, the moonlight dancing around the canopy of the forest, the warm breeze making them whisper. It was a bit hard to stop thinking of ghosts, but then a stray dog came by to may table, dropped at my feet and started snoring. I ate at ease.

The uncertainty didn't last much longer. The following day I went out for a run, meaning to get rid of crazy ideas, and once I came back home I was so tired that, after the shower, I dropped to the bed and fell dead asleep at once. I woke up around sunset, with the stereo filling the house with country. I was still sleepy, so I couldn't understand when I had turned it on, but I couldn't think of other explanations either. With my eyes still glued almost shut and yawning with all my power, I went down to the kitchen to have some water and a snack and saw dinner. There were no traces of someone having cooked, but the dinner was made at home: homemade pasta with parisienne sauce. The dish, still hot, lied on the island of the kitchen, next to a glass, a bottle of beer and a card. Surprised and still rather sleepy, I went and read it:

> Sorry for your confusion and loneliness. I hope you accept this offer as sign of riendship. I want to keep you company, but I'm afraid.

"Afraid of what?", I asked to the air, quite frustrated. I did not want to accept the offering, but I was starving and it smelled so good. I started eating, but after a few seconds I got up and checked the fridge and the freezer. Indeed, the food had been cooked with _my_ ingredients.

"I don't know where you are, whether you are hiding or what", I said to the air. "Thank you for cooking, but I was saving this for another day."

No answer. I kept eating, in silence.

"It's delicious, in any case. Well done", I mumbled.

I was sick of living by myself. I wanted to have maté with someone. I wanted to come back from work and have dinner already made. I left the fork on the plate to sweep away my tears. Oh, that someone cooked my favorite dish, and got it right. That someone cooked for me, and kept me company.

And kept me company.

I stood up to wash my face, wet and red. I turned around to go up the stairs to my bedroom, but on the way I clashed agains the giant cat uselessly standing there: it made me spin around and fall on the bench next to the staircase. I kept weeping. I leaned against the huge cat, which wrapped my shoulders with its tail.

I screamed.

Something clicked, and a flash blinded me.

I squeezed free of the cat but could not find its tail or any other change in it. I strode across the living room and checked the rectangular stone on top of the hearth. I swept my fingers across it, and a delicate panel slid to a side, revealing a built-in camera. I turned, and understood. The bench with the cat faced the camera: probably and ingenious setup to take elegant pictures from a distance. Ingenious, yes, but who turned it on?

"This is not funny!", I yelled, with a strangled voice. My eyes kept weeping, but I was livid. I stalked back across the living room, up the stairs and towards the locked room.

Its door opened.

The room was dark, barely illuminated by as mall window, but the light turned on automatically. In a corner there was a desk with a computer on, its screen off, and a printer. In a box under the desk there was a pile of empty frames and all and each of the walls were covered with identical pictures: someone sitting on the bench next to the staircase, next to the giant cat, wearing a sort of velvety scarf on the shoulder. But not identical, no. In each picture there was a different person: different ages, different genders, different colors and clothes and shapes. All of them scared to death. On the printer's tray there laid a picture: on the same bench, with the same cat, and me, pale, my eyes and nose red, frozen in a terrified expression.

I swallowed, breathed deeply and, slowly, trying not to make a noise, went to watch the pictures, going through all the walls, up to a group of photographs with fancy frames and colored stickers. There were ten of these, with one or more people *smiling*. There were pictures of a girl with her parents, the girl a bit older and alone, grown up and with a man, then with children, then the children grown up, and their children. I figured the shared figure was the owner of the house, who had voluntarily taken the pictures. The next ones were very different: the people were sitting on the same place and wearing the same scarf, but they were surprised and terrified. Watching more closely, I realized that it was no scarf after all: it was the tail of the giant cat. And the cat, always alert and serious, looked in the pictures placid and sweet.

I stepped back, still trying to grasp this. Tears were falling again, but not in my behalf. Another step. Oh, the loneliness. The fear. From the corner of my eye I saw the picture on the printer's tray, where my terror was immortalized. Softly, as if it was going to bite me, I stretched my hand and took it. Nothing happend. I went towards the door, and it did not close. I left the room and walked through the corridor and down the stairs. Silence dominated as if the world was holding its breath.

I left the air kept in my lungs, took another deep breath, and then another. I sat on the bench next to the staircase and looked at the giant cat, still a solemn statue covered in suede. I turned to look at the hearth and the rectangular stone. I kept staring as if the stone was the eyes of a tiger I'm trying to tame, and I smiled. Carefully, I tore the picture apart. I hugged the cat, still smiling.

"Now, one smiling", I said, and accepted the hug of its majestic tail. Barely audible, the house was purring.
