---
title: "Se busca compañía"
author: "Mariana Montes"
date: '2021-08-17'
slug: se-busca-compania
categories: fiction
tags: []
subtitle: ''
summary: 'Este es un cuento inspirado por una consigna del Mundial de la Escritura 2021 (en el que no participo). ¡Y lo traduje al inglés!'
authors: []
lastmod: "`r Sys.time()`"
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r, include = FALSE}
library(fontawesome)
up <- fontawesome::fa("star", fill = "#FFC300")
down <- fontawesome::fa("star", fill = "#98978b")
```

Estaba harta de vivir sola. No daba más. Nunca pensé que diría eso, porque disfruto de mi espacio personal, puedo pasar horas leyendo o mirando Netflix y YouTube o ahogándome en Twitter, pero si algo me enseñó este año de pandemia es que necesito compañía. Quiero sentarme a tomar mate con alguien, quiero que me abracen cuando miro películas dramáticas, quiero llegar a casa un día y que esté hecha la cena.

La soledad me estaba drenando, pero no se iba a ir por sí sola, así que me puse a buscar un lugar para mudarme. Un lugar *donde ya viviera alguien*. Encontré algunos foros donde se buscaba gente para convivir: ofrecían una habitación y compartir cocina y baño, y sólo tenías que pagar la mitad del alquiler. Me tiré en el sillón con la compu en el regazo y me puse a chequear las solicitudes, con crecientes bostezos y los párpados cada vez más pesados. Mi deseo por conseguir compañía competía con mi reticencia a compartir hogar con alguien desconocido. Encima tenían todo tipo de requisitos y el panel de filtros de la página era un desastre. Que no fumar, que aguantar fumadores, no hacer ruido después de las diez, tolerar ruido hasta las cuatro de la mañana, no traer animales, no ser alérgico a los gatos, tomar mate dulce, ser vegetariano, hablar francés...
Los que no tenían requisitos eran los más sospechosos ---al menos, no me daban pistas sobre qué tipo de gente eran en realidad. Cuando le escribí a una de esas me pidió que le mandara una foto y al toque respondió que "ya había encontrado a alguien más". Otro me pidió una foto de mi biblioteca y me dijo que tal vez tendría que invertir un poco más en filosofía antes de hablarle otra vez. Otra casa sin requisitos tenía tantas cruces y rosarios en las fotos de las habitaciones que me levanté a hacer un mate nuevo antes de seguir.

No sé cuántas casas miré antes de darme por vencida, se sintió como una eternidad. Estaba por cerrar la página y levantarme a hacer la cena cuando vi una foto de la cabaña más adorable del mundo y tuve que hacer click.

> Cabaña con parque y galería (hamaca incluida), tres dormitorios, cocina con isla y biblioteca multilingüe. Cochera techada, espacio para bicicletas y tres cuchas cubiertas. Dos dormitorios disponibles para quien quiera compartir espacio conmigo. Lamentablemente, no hay accesibilidad para sillas de ruedas por el momento. Requisitos: no fumar, mantener el orden en los espacios comunes, no romper muebles, no prender fuego la cocina, no rechazar animales callejeros.

Las fotos eran adorables. Había un living con empapelado, un gigantesco reloj de pared y un magnífico hogar empedrado. La "biblioteca" era una habitación completamente cubierta de estantes, con más libros de los que había leído en mi vida. La vista desde las ventanas de los dormitorios era de un verde profundo, con una decena de árboles entre la casa y la calle. Y el precio era exactamente lo que estaba dispuesta a pagar.

Un poco sospechoso. Nunca había escuchado de una casa así, y aunque no estaba en mi ciudad, estaba suficientemente cerca para que venir de visita no fuera tan difícil. Era casi como si me hubieran leído la mente... pensé en los algoritmos de estos sitios de búsqueda y que tal vez se fijaba en las cosas que me interesaban para crear la casa ideal. Miré las reseñas del sitio, pero no había ningún comentario. Busqué la dirección en Google Maps, para ver si había comentarios ahí, y casi todos eran negativos. Uno de tres años atrás decía que la zona no estaba muy iluminada, y otro más viejo aún se quejaba de que la reja estaba oxidada. Pero eran viejos. Uno más reciente leía:

> `r up` `r down` `r down` `r down` `r down`
>
> Demasiado verde, los domingos se llena de gente tomando mate entre los árboles y nadie los hecha, pero al momento que prendí un pucho se escuchó un grito como si estuvieran torturando a alguien.

Casi se me va el mate a la nariz. Pasé al siguiente comentario:

> `r up` `r up` `r down` `r down` `r down`
>
> No es un restaurante es una casa pribada.

> `r up` `r up` `r up` `r down` `r down`
> 
> Ni idea que tal, nunca fui.

Antes de que se me fueran los ojos al cerebro de tanto ponerlos en blanco, me fijé si había algún comentario positivo, y encontré uno solo, de un par de días atrás.

> `r up` `r up` `r up` `r up` `r up`
>
> Pasé por acá ayer, estaba lloviendo y esperé a que pasara la tormenta en la galería. Me daba miedo el bosque pero no pasó nada, vino un perro callejero y se sentó conmigo todo el rato. No sé quién vive acá pero me dejaron una taza de té en la ventana, gracias!

Convencida. Le escribí a la cuenta que había posteado en el otro sitio, y a los dos minutos me respondió con muy buena onda y me mandó el PDF del contrato. No había información del usuario: el nombre era CabañaEnElBosque666 y la foto era del reloj de pared en todo su esplendor. Pero me habían convencido; le mostré el contrato a una amiga que trabaja en eso, lo imprimí, lo firmé, me lo certificó, lo mandé por correo a la casa y me puse a planear la mudanza. A los dos días me llegó un sobre con mi juego de llaves y un frasco de plástico con galletas que me hizo explotar el corazón, aunque eran de panadería. Mi amiga, Sandra, me convenció de mandar mis muebles a un depósito por si acaso, y sólo me llevé ropa y algunas otras cosas a mi nuevo hogar.

Me daba mucha curiosidad saber quién sería mi anfitrión. Empecé a fantasear que tenía mi edad, le gustaba andar a caballo y cebaba unos mates que no se lavaban. Mientras terminaba de cargar las cosas en la camioneta de mi amiga, me imaginé cómo sería el primer momento en esa casa, quién me abriría la puerta: una figura suave, con una sonrisa luminosa, los cabellos colorados enroscados en una trenza elaborada que bajaba en espiral desde su frente hasta su nuca, su hombro, su pecho. Me imaginaba ojos del color de la madera del reloj, que nunca me acuerdo cómo se llama. Esa que es oscura, lustrosa, y sólo los ricos la tienen. Unas cuadras antes de llegar a la casa paramos en un semáforo frente a un laboratorio, y fantaseé que era su lugar de trabajo:

--Felipa Nosecuánto, química --se presentaría, y yo respondería con algo muy astuto, porque en esas fantasías sé cómo interactuar con gente.

--¿Tenés idea de con quién vas a estar viviendo? ---me preguntó Sandra, interrumpiendo mis fantasías.

--No sé, pero parece piola --respondí.

--Las galletas esas estaban muy buenas --acordó--, aunque eran de panadería. ¿Querés que me quede un rato con vos, así te llevo a mi casa si algo sale mal?

Negué con la cabeza. Estaba segura de que iba a salir bien.

La cabaña se veía tan adorable como en las fotos. El parque resplandecía bajo el sol de la tarde, y altos árboles (¿álamos?) bordeaban la callecita de entrada, que tenía sus baches. Sandra estacionó frente a la entrada y me ayudó con la primera carga de equipaje hasta la entrada. Busqué un timbre y llamé, pero no hubo respuesta. Golpeé la puerta, por si el timbre no andaba, pero tampoco. Decidí usar mi llave, y entramos. La puerta daba al living, tan elegante como en las fotos. El hogar estaba apagado pero el reloj de pared no andaba. Algo de polvillo flotaba en los haces de luz que entraban por las ventanas, pero estaba bastante bien ventilado. Junto a la entrada había un perchero, algo que parecía un estante para zapatos, un delicado espejo de pared y, pegada al espejo, una nota.

> ¡Bienvenida a casa `r fontawesome::fa("heart", fill = "red")`! Tu habitación es la segunda a la izquierda en la planta alta: las sábanas están limpias y hay acolchados en el armario. No hay comida en la cocina así que abajo hay números de delivery por si no querés cocinar. El súper también tiene delivery y son piolas. El WiFi es CabañaEmbrujada y la contraseña es k8NdSPkf3.

Después sólo había una lista para pedir comida y nada más. Sin firma (¿cómo se llamaba?) o información de cuándo nos íbamos a ver, si se había ido de viaje, o qué. Pero el mensaje era muy dulce, el nombre del WiFi era ingenioso y la contraseña estaba buena, aunque no memorable. Sandra me ayudó a llevar mis cosas a mi dormitorio, que tenía una cama de lo más atractiva, un balconcito con geranios y una espectacular vista al bosque, pesadas cortinas de blackout y un armario que podría llevarme Narnia, aunque no me animé a probar. Pedimos unas pizzas y Sandra me hizo compañía un rato, pero después tuvo que volverse a su casa y quedé sola. Otra vez.

La casa tenía sus aspectos positivos. Primero, era preciosa. Cada detalle arquitectónico y de diseño me encantaba, desde el tono blancuzco de las mesadas al tamaño de los cajones, desde la presión del agua en la ducha hasta la suavidad de los picaportes, desde la textura de las cortinas hasta el brillo del linóleo que cubría todos los pisos. Pero estaba vacía. No veía señal alguna de quien fuera que vivía ahí: sólo una habitación, al final del pasillo en la planta alta, que estaba cerrada con llave.

La primera noche, después de una buena ducha, me tiré en la cama y me dormí al instante. Al día siguiente guardé mi ropa en el armario mientras escuchaba música con mis auriculares ---después de tres canciones me di cuenta de que podía usar el estéreo, y llené la casa de country y pop. Poco a poco, la música me fue entusiasmando, y empecé a bailar mientras colgaba mis sacos, ordenaba mis zapatos y acomodaba los peluches en un estante. Bailé con una anfitriona imaginaria por el dormitorio y el pasillo, bajando la escalera y hasta la cocina, donde puse a calentar agua para el mate. Armé la lista de compras, seleccioné mis productos en la página del super y pedí que me lo mandaran por delivery (no fuera a ser que mi conviviente apareciera justo cuando yo no estaba). Armé el mate y me puse a explorar la casa, todavía con las caderas dominadas por la música.

El living lo conocía. En la pared de entrada había un televisor bastante moderno (SmartTV probablemente) pero estaba desenchufado; del otro lado había un sillón con forma de L, con los almohadones un poco polvorientos pero muy cómodos, y en el medio una mesita de té acumulaba algo de polvo sobre un par de cómics. El otro brazo de la L enfrentaba el hogar, que aunque apagado parecía funcional, y era tan grande que podría haberme sentado adentro. Tenía una repisa, pero no había fotos ni adornos, excepto por una especie de piedra rectangular fijada a la pared, y encima sólo estaba el reloj magnífico de las fotos. Frente al hogar y el reloj estaba la escalera, perpendicular, con una decoración bastante intrigante. Era un banco construido del mismo material que la escalera, con almohadones finos y, a un costado, un pilar con forma de gato. Como si un gato delgado y muy elegante, de dos metros de altura, estuviera sentado junto al banco, sus orejas atentas tocando el cielorraso. El material era extraño, como si estuviera forrado en gamuza. Más extraña era la ubicación, como si alguien quisiera sentarse en el banco, junto al gato gigante, para mirar el reloj o el fuego en el hogar, pero desde el otro extremo del living.

La planta baja tenía, entonces, la cocina, el living, la biblioteca, el baño más claustrofóbico del mundo (con sólo un inodoro) y una cochera-depósito. La planta alta tenía tres habitaciones y el baño con bañera, ducha, una amplia mesada con un espejo con lamparitas, inodoro y bidet, y un cartelito con una flecha apuntando a un botón para encender un extractor. Una de las habitaciones estaba abierta, vacía y sin usar, y si nadie me lo impedía pensaba usarla de oficina, aunque la cama era tentadora. Otra habitación era mi dormitorio, y la tercera, la puerta al fondo del pasillo cerrada con llave, parecía como si no la hubieran abierto en décadas, aunque debía ser el otro dormitorio en uso. También había un ático con juegos de mesa cubiertos de polvo y un parque inmenso que me tomó una tarde entera explorar por completo.

Al final del segundo día Sandra me llamó mientras preparaba la cena. Conecté los auriculares a la computadora y la dejé en un punto de la cocina donde podíamos vernos mientras trabajaba.

--¿Y? ¿Novedades de tu "conviviente"? --me preguntó inmediatamente, con un tono jocoso pero probablemente preocupada.

--Nada --contesté mientras picaba la cebolla--, ningún mensaje, ninguna llamada, ningún rastro en la casa. No sé, es como si estuviera viviendo sola otra vez.

En algunas circunstancias, puede ser útil estimular los lagrimales con cebolla y hacer de cuenta que no hay nada emocional de por medio. Me lavé las manos y la cara y volví a la mesada para picar el jamón, la pechuga y los hongos.

--Qué cosa rara, che. ¿Probaste escribirle otra vez por BuscoCompañía? Era esa la página, ¿no?

--Sí, pero no hay caso. La cuenta no existe más. Sus mensajes en mi conversación están borrados, censurados, no sé.

--¿Y no tenés ningún número de teléfono?

--El de la casa nomás. --Respondí con una carcajada, y me fui a lavar las manos otra vez antes de prender el fuego bajo la sartén--. No pensé que iba a necesitar otra forma de contacto, viste. Me fijé en el contrato y sólo está la dirección, y nada más. No sé, será cuestión de esperar... Es una decepción nomás.

Puse manteca sobre la sartén caliente, y una vez derretida empecé a agregar la cebolla, el pollo, el jamón y los hongos, uno a uno, mientras Sandra y yo intercambiábamos hipótesis sobre qué le habría pasado a mi supuesta anfitriona (en mi cabeza era la mujer de mis sueños todavía), desde una emergencia familiar en la otra punta del país a una explosión en el laboratorio en el que yo imaginaba que trabajaba e incluso que los extraterrestres la habían secuestrado. Sandra fue la que lo sugirió:

--¿Y si la casa está embrujada y estás hablando *con un fantasma*?

Ahogué una risa nerviosa, agachándome para sacar la harina del armario así ella no veía lo nerviosa que era mi risa.

--Al menos un fantasma es mejor que estar sola, ¿no? --Dijo con el tono más ligero que pudo concebir.

--Supongo... --murmuré, mezclando la harina en la salsa, y concentrándome en agregar la leche y mezclar, agregar leche y mezclar... No quería que mis oídos se pusieran a buscar sonidos misteriosos, pasos en una habitación vacía, un televisor desenchufado que se encendía, o...

--Ok, aguantame un segundo --dijo Sandra, y su seriedad me sacó del trance.

--¿Qué pasa? --Pregunté, bajando el fuego de la sartén y preparándome para amasar los fideos. Puse agua a hervir, instalé la pequeña pastalinda en la mesada, saqué la masa de la heladera, espolvoreé harina y me puse a cortar y aplanar. En la pantalla de la computadora, Sandra miraba con el entrecejo fruncido: no a mí, sino a alguna otra cosa que buscaba por su lado.

--El otro día me enteré de una página llamada estaembrujada.com --dijo, con la voz perdida mientras sus esfuerzos se concentraban en la búsqueda--. ¿Cuál era la dirección? Los Robles...

--Avenida Los Álamos 3. ¿estaembrujada.com dijiste?

--Ajá --respondió, aún un poco distraída--. ¡Ja! Podés usar Google Maps para elegir también. Tiene como colorcitos y categorías... Mirá. Se fija si hay como reportes de fantasmas, o la frequencia de mudanzas...

--Si murió alguien... --bromeé, incrédula, rotando la manija de la pastalinda más de la cuenta.

--Si murió alguien --confirmó Sandra con seriedad, y de repente pegó un grito de triunfo, aplaudió... y volvió a la expresión confundida--. Dice "indefinido: puede estar embrujada, con 56% de probabilidad".

--Ah, bueno, ¿*probabilidad*? --Pregunté, otra vez con risa nerviosa, y me volteé para agregarle sal al agua y poner a hervir los fideos.

--Sip --Sandra estaba muy seria, como si estuviera leyendo el diagnóstico de un médico--. Dice que no hay historial de muertes... O sea, la primera dueña se murió, pero no en la casa. Algo así como que fue de visita a lo de su hija y sus nietos, se quedó a dormir y nunca más despertó. Nadie se hizo cargo de la casa, pero de vez en cuando alguien alquila una habitación de alguna forma (por internet como vos, supongo) y a los dos o tres días se va...

--¡¿A los dos o tres días?! --Grité, casi dejando caer la vajilla que tan ordenadamente estaba disponiendo en una bandeja.

--Relajate, seguro que no es nada --Sandra me intentó calmar sin éxito--. Pero cualquier cosa, me avisás. No hay reportes de que nadie se haya muerto ahí, así que no creo que estés en peligro.

La miré con incredulidad. Oh, bien, podría ser una casa embrujada, pero al menos no me iba a *matar*.

--Ok, gracias --Le dije, no sin cierta frialdad--. La cena está lista, así que te dejo.

--Te hiciste la salsa parisienne --notó con una sonrisa, sin volver a mencionar el tema--. ¿Por qué la bandeja?

--Voy a comer a la galería, la noche está linda. ¡Buenas noches!

--Buen provecho --me deseó, y lanzó un beso a la pantalla--. Y cuidate.

Asentí, corté la conexión, y fui con mi cena a la galería. La luz automática se encendió apenas salí y por un momento me dio un escalofrío. Me detuve a respirar hondo tres veces antes de ir hasta la mesa y sentarme. La noche estaba hermosa, la luz de la luna jugaba con las copas de los árboles, y una brisa cálida los hacía susurrar. Me costó un poco dejar de pensar en fantasmas, pero luego un perro callejero vino hacia mi mesa, se echó a mis pies y empezó a roncar. Comí tranquila.

La incerteza no duró mucho más. Al día siguiente salí a correr, para despejarme de ideas descabelladas, y cuando volví estaba tan cansada que, después de la ducha, me desplomé en la cama y me dormí al instante. Desperté hacia el anochecer, con el estéreo llenando la casa de country. Todavía estaba somnolienta, así que no podía entender en qué momento lo había prendido, pero tampoco se me ocurrían otras explicaciones. Aún con los ojos pegados por lagañas y bostezando con todas mis fuerzas, bajé a la cocina para tomar agua y comer algo, y vi la cena. No había rastros de que alguien hubiera cocinado, pero la cena era casera: fideos caseros con salsa parisienne. El plato, aún caliente, esperaba sobre la isla de la cocina, junto a un vaso, una botella de cerveza y una tarjeta. Asombrada y aún algo adormecida, me acerqué a leer:

> Perdón por tu confusión y tu soledad. Espero que aceptes esta ofrenda como señal de amistad. Quiero acompañarte, pero tengo miedo.

--¿Miedo de qué? --Le pregunté al aire, algo frustrada. No quería aceptar la ofrenda, pero tenía hambre y olía muy bien. Empecé a comer, y después de unos segundos me levanté y chequeé la heladera y el freezer. En efecto la comida había sido hecha con _mis_ ingredientes.

--No sé dónde estás, si te estás escondiendo o qué --Dije al aire--. Muchas gracias por cocinar, pero estaba reservando esto para otro día.

No hubo respuesta. Seguí comiendo, en silencio.

--Está rico, igual. Bien hecho --murmuré.

Estaba harta de vivir sola. Quería tomar mate con alguien. Quería volver de trabajar y que la cena estuviera hecha. Dejé el tenedor sobre el plato para enjugarme las lágrimas. Oh, que alguien me cocinara mi plato preferido, y le saliera bien. Que alguien cocinara para mí, y me acompañara.

Y me acompañara.

Me levanté para lavarme la cara, húmeda y enrojecida. Me volteé y encaré hacia la escalera para ir al dormitorio, pero choqué con el gato gigante parado ahí para nada: me hizo rotar sobre mi eje y caí sentada en el banco al lado de la escalera. Seguí llorando. Me recosté contra el gato gigante, me rodeó los hombros con su cola.

Grité.

Algo hizo click, y un flash me encandiló.

Me zafé del gato con un salto, pero no veía su cola ni ningún otro cambio. Crucé el living y examiné la piedra rectangular extraña sobre el hogar. Deslicé los dedos sobre el lado que me enfrentaba, y un panel delicado se desplazó a un lado, revelando una cámara empotrada. Me volteé, y entendí. El banco con el gato enfrentaban la cámara: probablemente una disposición ingeniosa para sacar fotos elegantes a distancia. Ingenioso, sí, pero ¿quién lo activó?

--¡No es gracioso! --grité, con la voz atragantada. Mis ojos seguían llorando, pero estaba furiosa. Volví a cruzar el living a zancadas, subí la escalera de dos en dos y me dirigí al dormitorio cerrado con llave.

La puerta se abrió.

La habitación estaba a oscuras, apenas iluminada por una ventana pequeña, pero la luz se encendió automáticamente. En un rincón había un escritorio con una computadora encendida, pero monitor apagado, y una impresora. En una caja bajo el escritorio había una pila de portarretratos y todas y cada una de las paredes estaban cubiertas de fotos iguales: alguien sentado en el banco junto a la escalera, al lado del gato gigante, con una especie de bufanda aterciopelada colgando de un hombro. Pero no eran iguales. En cada foto había una persona distinta: distintas edades, distintos sexos, distintos colores y ropas y formas. Todos aterrorizados. En la bandeja de la impresora había una foto: en el mismo banco, con el mismo gato, y yo, pálida, con los ojos y la nariz rojos, congelada en una expresión de espanto.

Tragué saliva, tomé aire, y lentamente, intentando no hacer ruido, me puse a mirar las fotos, recorriendo todas las paredes, hasta llegar a un grupo de fotos con marcos elaborados y stickers de colores. Eran diez fotos, con una o más personas *sonrientes*. Había fotos de una niña con sus padres, de la niña sola más crecida, adulta y con un hombre, luego con niños, luego los niños crecidos, y sus niños. Supuse que el eje era la primera dueña de la casa, y que había tomado las fotos por su propia cuenta. Las siguientes eran muy distintas. Las personas estaban sentadas en el mismo lugar y usaban la misma bufanda, pero estaban sorprendidas y aterrorizadas. Mirando con más atención, me di cuenta de que no era una bufanda: era la cola del gato gigante. Y el gato, que siempre miraba atento y serio, en las fotos tenía una expresión plácida y adorable.

Di un paso atrás, incrédula. Mis lágrimas caían otra vez, aunque no por mí. Otro paso. Oh, la soledad. El miedo. Por el rabillo del ojo miré la foto en la bandeja de la impresora, donde mi horror estaba inmortalizado. Con delicadeza, como si me fuera a morder, extendí la mano y tomé la foto. No pasó nada. Fui hacia la puerta, y no se cerró. Salí de la habitación, crucé el pasillo y bajé la escalera. Un silencio dominaba como si el mundo estuviera contiendo la respiración.

Largué el aire contenido en mis pulmones, respiré hondo, y otra vez. Me senté en el banco junto a la escalera y miré al gato gigante, aún una solemne estatua tapizada en gamuza. Me volteé a mirar hacia el hogar y la piedra rectangular. Sostuve la mirada como si la piedra fueran los ojos de un tigre que intento domar, y sonreí. Con cuidado, rompí la foto. Abracé el gato, aún sonriendo.

--Ahora una sonriendo --dije, y acepté el abrazo de su cola majestuosa. Apenas audible, la casa ronroneaba.

