---
title: All of my selves
author: Mariana Montes
date: '2021-03-29'
slug: all-of-my-selves
categories: []
tags:
  - Writing
  - Research
subtitle: ''
summary: ''
authors: []
lastmod: '2021-03-29T19:11:16+02:00'
featured: no
image:
  caption: "Warning to be kind to the reader, in [Hadley Wickam's Advanced R](https://adv-r.hadley.nz/functionals.html#map)"
  focal_point: ''
  preview_only: no
projects: []
---

We learn and forget, we discover new perspectives, we change moods, we get used to things. It makes sense to think that the Mariana from 10 years ago is not the Mariana writing this post, but even the Mariana from a couple of days ago is different. It might seem funny, or even scary, to decouple of oneself and think of your previous of future selves as actually different people. But it can also be useful, especially if you tend to be harsher to yourself than to others --then maybe, even for a moment, you can be proud of those other selves.

I have all kinds of emotions and relationships with my other selves. I try to be forgiving, and keep in mind that if I am consequent and honest with myself and do what I can, I can trust that what my old self did was what she could. She didn't see those other options? Well, she didn't, she acted based on what she did know. She wasn't so productive that day? Well, she felt down, I can't just project my current mood and availability on other circumstances. I try not to be disappointed on my past selves, and trust they did what they could[^self-esteem]. But beyond that, I want to talk about the relationship between our sequence of selves, writing, and research.

[^self-esteem]: I wish I could tell you that's the antidote for low self-esteem, but I'm afraid that's not the case. It might make it better, though.

## I don't understand my old self anymore

At one of the stages of my PhD (but also before, when I worked on metaphor), I had to annotate concordance lines. I will describe this assuming you have no idea what this kind of work looks like.

First, you have access to a corpus: a large collection of texts. Imagine you take your whole library, in digital form, but probably bigger. Then, you look up a word, like in a Google search, and you collect all the results with a bit of context on each side. Let's suppose the word you are researching is *church* (which was my case for a while).

My work consisted on looking at all those instances of *church* and assigning each of them a sense. You could have a list of dictionary senses, but I mixed that with an inductive method: I created categories that made sense based on my specific sample (organization, as in *The church forbids X*; community, as in *The woman from that church*; building, as in *They built a new church*, etc.), and manually classified all the instances. Hundreds of them. Sometimes I had to arrange the classification, sometimes I had to stare at a line for a while until I understood it.

And sometimes I went back to a line after a couple of weeks and had *no idea* why it was annotated the way it was. The "right" answer was obvious, but what I had filled in was different. What was going on? I felt I couldn't trust myself, that if I had to double- or triple-check everything I would never end... But it was not so terrible --at least, I noticed it!

On the one hand, it was quite rare. Most of the time I either agreed with that past self or actually changed my mind and noticed it.
On the other hand, we make mistakes, it happens. If we have to type, there will be typos. If we have to do repetitive work, we might slip. If we cannot properly distinguish one line from the one below, we might insert text in the wrong place. We cannot live afraid of messing up and constantly nervous about getting it perfect all the time. Instead, I prefer to live with the knowledge that I may make mistakes, write code wrong, make typos, etc., and put measures in place for it. Test my code (seriously, test your code, every small piece of it). Check the coherence of my data. Give myself time to review what I wrote. If I know where I might mess up, I can keep an eye for it --if I'm constantly trying to get things right immediately, I might believe that I couldn't possibly make a mistake and get even more frustrated when I find it, too late.

Because I will. Because we cannot see everything and understand everything and remember everything. Because research is done in community, compensating each researcher's partiality (limited perspective, memory, interests) with other researchers'. And that other researcher can be yourself, in another moment, with another perspective and memories and understanding.

## I want my future self to understand me

If I cannot really trust past selves to be infallible, I cannot expect my future selves to think I am, right? If I cannot remember what I was thinking when I did that thing the other day, I should know, tomorrow's self will have a different idea of what I am thinking now. She may forget. She may misremember. She might have more important things to focus on.

Future self's solution to the discontinuity between ourselves is to forgive, to be ready to deal with the discrepancies. From the other perspective, as a way to lighten future self's burden, the solution is to register. *Write it down*.

It could be just a log --a daily or weekly register of what you have done, so future self can be proud, and also check when that event took place so many years ago. Make it a journal if you want. It could also be reports, which is how I started with R Markdown. Partially, I wanted to describe what I was doing so if anyone asked (e.g. if my supervisors wanted more detail), it was there already. But I also wanted to try and put into words the reasoning behind my code, my plots, my whole workflow. What decisions did I make, and why? Where can I read more about it? The most interesting thing with this kind of writing[^notebooks] is that you can write down your thinking, link to the data, reveal the actual code --exposing it to your or other people's scrutiny-- and/or its output, and alternate with plots made with that same code. Everything is together in one package (the notebook itself or the directory), open and honest and declared.

[^notebooks]: This can also be done in [Jupyter Notebooks](https://jupyter.org/), which were originally for **Ju**lia, **Pyt**hon and **R**, and in [ObservableHQ](https://observablehq.com), for Javascript, which I dove into recently.

I know that "exposing it to your or other people's scrutiny" can sound uncomfortable, if not terrifying, but that is what research is about. Peer review is the most obvious instance, but for that to go well your work should have already gone through previous sieves, such as conferences, talks with colleagues, etc. Why? Because we have a limited perspective, memory, and interests, and it is really really hard to get out of them without combining them with someone else's perspective, memory and interests. Because research is made in community. It is hard to take criticism, specially if your whole life you have been taught that making mistakes is bad, that there is a right answer to everything and you should be able to find it. I am still struggling with that, even though I "know" that all that is harmful.

Now, maybe you can count on your future self on being kinder to your past/current self? (After all, they would be the ones taking the criticism for you, right?) Then keeping everything written, explaining what you thought, will help them. Because they might have forgotten. Which is good, because then they are a *different* mind in conversation with you, bringing a different perspective that --amazingly-- was actually possible thanks to the thinking process that you already made. You can be a whole scientific team spread in time. (Of course, even then your perspective is more limited than if you partner with other fully different people.)

## Thank you, past self

Have you ever had that feeling? You wish you had something done --that you had bought icecream earlier, that you had set up an alarm to pick up the laundry, that you had saved the link for that awesome post... and then you realize you actually had? But you don't have any recollection of it, or at least not until you find the icecream in the freezer, your alarm rings or you find the link to the post. I relate this to the same discrepancy I mentioned before: the person that did those things was past me, not current me, and was smarter than I thought, had more foresight than I gave her credit for.

We might have a greater tendency to feel disappointed on our old selves than to feel grateful or proud. Of course, it depends on your personality, I think. I focus on getting ready to forgive my past selves, but feeling proud and grateful is not so easy. I could try and feel proud of my "current" self, of what I had *become*, but not of the multiple decisions and actions that had made it possible.

I think that changed when I got my PhD position in Belgium. Of course, my degree made it possible, but the specifics of the job ---learning about cognitive linguistics, some knowledge of statistics, programming, corpus analysis---, those I got outside the curriculum. I must thank specially my dad, for giving me so many tools and encouraging me to pursue this, and of course to the research team in Córdoba that kept me under their wing during that time.

But I have to thank that old me that started reading about cognitive linguistics as soon as she opened
[that first book](https://www.routledge.com/Cognitive-Linguistics-An-Introduction/Evans-Green/p/book/9780805860146),
and kept doing it after school, because it didn't feel like studying. I must thank her for seeking the research team in the first place, and for the thorough work she did reading and analyzing, for spending summers trying to figure out statistics (thanks mom for guiding me there!), for reading about R, sitting down with dad to learn Python.

I tend to focus a lot on the privilege that made this possible --on my awesome parents willing to teach me what they know and to give me the tools to learn what they don't, who gave me the opportunity to study without having to work at the same time, and in a loving, encouraging environment; on the free education; on my access to resources. But I must be grateful of past Mariana for taking all that and working with it, not because she knew what was coming but because she was passionate and driven, and she wanted to build herself regardless of where that took her.

---

I hope you can also be kind to your other selves: forgive and thank your past selves, and collaborate with your future selves. Maybe go read Heinlein's [*All You Zombies*](https://gist.github.com/defunkt/759182/ad44c6135d168ae54503a281bb7e1a24c6c2ea0c), too, it's awesome.